// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjOdOLocGsVDgsTWyqie-M-bkCAOCkZg',
    appId: '1:19815214552:web:242e8632589e5bde4c16ad',
    messagingSenderId: '19815214552',
    projectId: 'loginwidgets',
    authDomain: 'loginwidgets.firebaseapp.com',
    storageBucket: 'loginwidgets.appspot.com',
    measurementId: 'G-R6RSZ742XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRuHyD_gzZDV-_lokXlavKu99RUAC-Vo',
    appId: '1:19815214552:android:c5f73e4721e208b04c16ad',
    messagingSenderId: '19815214552',
    projectId: 'loginwidgets',
    storageBucket: 'loginwidgets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqSgFgaXhrBsOL1VynY-yKZhlD3qFIVio',
    appId: '1:19815214552:ios:a3d251de2d53bb9d4c16ad',
    messagingSenderId: '19815214552',
    projectId: 'loginwidgets',
    storageBucket: 'loginwidgets.appspot.com',
    androidClientId: '19815214552-pibf6bbhm1oj66lsii4g0p6sa32ons91.apps.googleusercontent.com',
    iosClientId: '19815214552-k2826f7g71rauosd4rqsjub43icqe4tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginwidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqSgFgaXhrBsOL1VynY-yKZhlD3qFIVio',
    appId: '1:19815214552:ios:14288364f9cb66f94c16ad',
    messagingSenderId: '19815214552',
    projectId: 'loginwidgets',
    storageBucket: 'loginwidgets.appspot.com',
    androidClientId: '19815214552-pibf6bbhm1oj66lsii4g0p6sa32ons91.apps.googleusercontent.com',
    iosClientId: '19815214552-hijqs8i055f96ih11hnlfbfb3iesv22s.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginwidgets.RunnerTests',
  );
}
